services:
  database:
    image: "postgres:16.11-alpine3.23"
    env_file:
      - ../.env.development
    ports:
      - 5432:5432
# DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB
